/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersRoute } from './routes/users'
import { Route as AboutRoute } from './routes/about'
import { Route as IndexRoute } from './routes/index'

// Create/Update Routes

const UsersRouteWithChildren = UsersRoute._addFileChildren()

const AboutRouteWithChildren = AboutRoute._addFileChildren()

const IndexRouteWithChildren = IndexRoute._addFileChildren()

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteWithChildren
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteWithChildren,
  AboutRouteWithChildren,
  UsersRouteWithChildren,
})

/* prettier-ignore-end */